version: "3"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
