import type { Metadata } from "next";
//import { Inter, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { MapProvider } from "@/contexts/map";

/*
const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter">
        <MapProvider>{children}</MapProvider>
      </body>
    </html>
  );
}
